### ISSUE TITLE
Datepicker's calendar icon button should be focusable 

### ISSUE THREAD

**Issue by rmnturov** [positive-js/mosaic#110]
**I'm submitting a bug**

- [x] bug
- [ ] feature request
- [ ] question

**What is the current behavior?**
Datepicker's calendar icon button should be focusable, button should have a focus state

**If the current behavior is a bug, please provide the steps to reproduce it**
1. Set focus to calendar input
2. Press Tab
3. Focus goes outside the control to the next focusable page element
  
**What is the expected behavior?**
1. Set focus to calendar input
2. Press Tab 
3. Focus goes to calendar button with icon
4. Button is highlighted (visually visible focus state)   

**Please tell us about your environment:**

- Mosaic version: 1.0.0-beta.5 (791d50c)
- Browser: Chrome 73.0.3683.103 (Официальная сборка), (64 бит)

**Comment by roll314** [comment]
PR is https://github.com/positive-js/mosaic/pull/114
