### ISSUE TITLE
Focus isolation inside datepicker's dialog

### ISSUE THREAD

**Issue by rmnturov** [positive-js/mosaic#111]
**I'm submitting a bug**

- [x] bug
- [ ] feature request
- [ ] question

**What is the current behavior?**
Datepicker's dropdown dialog loses focus on Tab navigation.

**If the current behavior is a bug, please provide the steps to reproduce it**
1. Set focus to calendar input
2. Dialog opens
3. Focus is set to current date button
4. Press Tab
5. Focus moves outside the dialog to any next focusable page element
5. Dialog is not closed
  
**What is the expected behavior?**
Focus should be isolated inside datepicker's dialog. Tab from the last focusable element should move focus to the first one
1. Press calendar button inside the datepicker's input
2. Focus moves to calendar grid
3. Current value is highlighted
3. Press Tab
4. Focus moves to period-button

**Please tell us about your environment:**
- Mosaic version: 1.0.0-beta.5 (791d50c)
- Browser: Chrome 73.0.3683.103 (Официальная сборка), (64 бит)

**Comment by roll314** [comment]
For a first sight it looks like we have correct behavior now, ie we can move calendar's date using arrow keys. It looks more useful for me than tab one-by-one focus change. For example we could change the week using arrow up key instead of 7 times pressed tab.

@mikeozornin, could u pls specify target behavior?

**Comment by mikeozornin** [comment]
Я думал успею быстро описать поведение всех компонентов (навбары, селекты и прочее) исходя из подобной логики, но видимо быстро не успею. Давайте починим это не дожидаясь тех.

Рома прав, если зациклить фокус внутри диалога будет лучше. Нужно переходить с даты на выбор месяца по Tab, а с месяца на даты по Shift + Tab, остальное все ок.

Нарисовал вот иллюстрацию:
![image](https://user-images.githubusercontent.com/1744928/57308669-7392b580-70ef-11e9-9259-73e35f21af5f.png)
