### ISSUE TITLE
Issues from sonar (bugs and critical code smells)

### ISSUE THREAD

**Issue by imrekb** [positive-js/mosaic#471]
**I'm submitting a**

- [x] bug
- [ ] feature request
- [ ] question

**What is the current behavior?**

https://sonarcloud.io/project/issues?id=positive-js_mosaic&resolved=false&tags=github-issues

**What is the expected behavior?**

Code haven't these issues 

**Please tell us about your environment:**

- Mosaic version: 9.1.x
- Browser: [all]

**Comment by KuryakovDen** [comment]
#490

**Comment by KuryakovDen** [comment]
#491
