### ISSUE TITLE
mcInput haven't [name] binding

### ISSUE THREAD

**Issue by evilfant** [positive-js/mosaic#94]
**I'm submitting a**

- [x] bug
- [ ] feature request
- [ ] question

**What is the current behavior?**
If I set [name] binding to mcInput it's not passed to input element

**If the current behavior is a bug, please provide the steps to reproduce it**
```typescript
// component.ts
...
nameField: string = 'some-name';
...
```
```html
<!-- template.html -->
<mc-form-field>
        <input [name]="nameField" mcInput [(ngModel)]="value" type="text">
</mc-form-field>
```
![2019-02-21 10 26 22](https://user-images.githubusercontent.com/6253480/53151221-ac78bf00-35c3-11e9-98b4-96d159425fcf.png)

**What is the expected behavior?**
[name] binding is passed to input element, it should generate
```html
<input class="mc-input ng-pristine ng-valid ng-touched" mcinput="" type="text" name="some-name" ng-reflect-name="some-name" ng-reflect-model="" ng-reflect-type="text" id="mc-input-0">
```

**Please tell us about your environment:**

- Mosaic version: 1.0.0-beta.0
- Browser: all

**Other information**

**Comment by imrekb** [comment]
In this case, name is attribute and isn't property. See [Attribute Binding](https://angular.io/guide/template-syntax#attribute-binding).

**Comment by evilfant** [comment]
ok, but
```html
<input [name]="nameField">
```
works fine, and
```html
<input mcInput [name]="nameField">
```
not working

**Comment by lskramarov** [comment]
because
[name]="nameField" is binding
and
name="nameField" is attribute
I think you have to read information given by @imrekb
